name:
    - 'a photo of the {} shoes.'
    - 'a photo of a {} sneakers.'
    - 'a photo of the {} shoes.'

brand:
    - 'shoes made by the {}.'
    - '{} is brand of this shoes.'
    - 'a photo of the {} shoes.'

color:
    - 'a photo of the {} color shoes.'
    - 'a photo of a {} shoes.'
    - 'Color of shoes is {}'

hightop:
    - 'a photo of the {}top shoes.'
    - 'a photo of a {}top sneakers.'
    - 'a bright photo of the {}top sneakers.'

zeroshot:
    - 'A photo of the {} shoes, brand is {}, color is {}, hightop is {}top.'
    - 'Brand is {}, a photo of a {} shoes, color is {}, hightop is {}top.'
    - 'Brand is {}, color is {}, a photo of a {} shoes, hightop is {}top.'
    - 'Brand is {}, color is {}, hightop is {}top, a photo of the {} shoes. '

