name:
    - 'a photo of the {} shoes.'
    - 'a photo of a {} sneakers.'
    - 'a photo of the {} shoes.'

brand:
    - 'shoes made by the {}.'
    - '{} is brand of this shoes.'
    - 'a photo of the {} shoes.'

color:
    - 'a photo of the {} color shoes.'
    - 'a photo of a {} shoes.'
    - 'Color of shoes is {}'

hightop:
    - 'a photo of the {}top shoes.'
    - 'a photo of a {}top sneakers.'
    - 'a bright photo of the {}top sneakers.'

zeroshot:
    - 'A photo of the {} shoes. Brand is {}, color is {}, hightop is {}top.'
    - 'Brand is {}. A photo of a {} sneakers. Color is {}. hightop is {}top.'
    - 'Brand is {}, color is {}, hightop is {}top. A photo of the {} sneakers. '
