name:
    - 'a photo of the {} shoes.'
    - 'a photo of a {} sneakers.'
    - 'a photo of the {} shoes.'

brand:
    - 'a photo of the {} brand shoes.'
    - 'a photo of a {} brand sneakers.'
    - 'a bright photo of the {} brand sneakers.'

color:
    - 'a photo of the {} color shoes.'
    - 'a photo of a {} color sneakers.'
    - 'a bright photo of the {} color sneakers.'


hightop:
    - 'a photo of the {}top shoes.'
    - 'a photo of a {}top sneakers.'
    - 'a bright photo of the {}top sneakers.'

sole:
    - 'a photo of the shoes of sole is {}'
    - 'a photo of a sneakers of sole is {}'
    - 'a bright photo of the sneakers of sole is {}'

zeroshot:
    - 'A photo of the {} shoes, brand is {}, color is {}, top is {}top.'
    - 'Brand is {}, color is {}, a photo of a {} shoes, top is {}top.'
    - 'Brand is {}, color is {}, top is {}top, a photo of the {} shoes.'

zeroshot_with_sole:
    - 'A photo of the {} shoes, brand is {}, color is {}, top is {}top, sole is {}.'
    - 'Brand is {}, color is {}, a photo of a {} shoes, top is {}top, sole is {}.'
    - 'Brand is {}, color is {}, top is {}top, a photo of the {} shoes, sole is {}.'

