name:
    - 'shoes made by the {}.'
    - '{} is brand of this shoes.'
    - 'a photo of the {} shoes.'

brand:
    - 'shoes made by the {}.'
    - '{} is brand of this shoes.'
    - 'a photo of the {} shoes.'

color:
    - 'a photo of the {} color shoes.'
    - 'a photo of a {} shoes.'
    - 'Color of shoes is {}'

hightop:
    - 'a photo of the {} shoes.'
    - 'a photo of a {} sneakers.'
    - 'a bright photo of the {} sneakers.'